services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./hospital-client
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
